import asyncio
import json
import faiss
from redis.asyncio import Redis
from motor.motor_asyncio import AsyncIOMotorClient
import numpy as np

#Is responsible for uploading and querying the vector database for image embeddings.
#The vector database will store the image embeddings generated by the embedding service, 
# and will allow for efficient querying of similar images based on their embeddings.

#Listens for the embedding service to publish new embeddings, and stores them in the database.
#Listens for the CLI to query for similar images, and retrieves the relevant embeddings from the 
# database to return the results.

r = Redis(host='localhost', port=6379, decode_responses=True)
pubsub_embeds = r.pubsub()
pubsub_queries = r.pubsub()

client = AsyncIOMotorClient("mongodb://localhost:27017")
db = client["vector_db"]
collection = db["images"]

DIMENSION = 3
EPSILON = 0.75
TOP_K = 10
base_index = faiss.IndexFlatL2(DIMENSION)
index = faiss.IndexIDMap(base_index)

#Gets service ready to listen
async def start():
    await pubsub_embeds.subscribe("image.embedding_results")
    print("[vector_db] Listening on image.embedding_results")
    await pubsub_queries.subscribe("query.images")
    print("[vector_db] Listening on query.images")
    

    await r.sadd("services_ready", "vector_db")
    await r.publish("service.ready", "vector_db")

    embed_task = asyncio.create_task(listen_embeddings())
    query_task = asyncio.create_task(listen_queries())

    try:
        await asyncio.gather(embed_task, query_task)
    except asyncio.CancelledError:
        print("[vector_db] Shutting down listener...")
    finally:
        embed_task.cancel()
        query_task.cancel()
        try:
            await asyncio.gather(embed_task, query_task)
        except asyncio.CancelledError:
            pass
        await r.srem("services_ready", "vector_db")

        await pubsub_embeds.unsubscribe("image.embedding_results")
        await pubsub_queries.unsubscribe("query.images")

        await pubsub_embeds.close()
        await pubsub_queries.close()
        await r.aclose()

#Listen Loop
async def listen_embeddings():
    async for message in pubsub_embeds.listen():
        if message["type"] == "message":
            await upload_embedding(message)

#Listen Loop
async def listen_queries():
    async for message in pubsub_queries.listen():
        if message["type"] == "message":
            await query_similar_images(message)

async def get_next_faiss_id() -> int:
    """Atomically increments and returns the next FAISS ID from MongoDB."""
    result = await collection.find_one_and_update(
        {"_id": "faiss_counter"},
        {"$inc": {"seq": 1}},
        upsert=True,
        return_document=True  
    )
    return result["seq"]

async def upload_embedding(message):
    image_id = None
    try:
        data = json.loads(message["data"])
        image_id = data["image_id"]
        embedding = data["embedding"]
        inference = data["inference"]
        print(f"[vector_db] Received embedding for image: {image_id}")

        vector = np.array([embedding], dtype="float32")

        faiss_id = await get_next_faiss_id()
        ids = np.array([faiss_id], dtype="int64")

        index.add_with_ids(vector, ids)

        await collection.insert_one({
            "faiss_id": faiss_id,
            "image_id": image_id,
            "inference": inference
        })

        print(f"Successfully inserted image embedding with image_id {image_id}")

    except Exception as e:
        print(f"Upload failed for image_id {image_id}, Error: {e}")

async def query_similar_images(message):
    try:
        data = json.loads(message["data"])
        query = data["tag"]
        event_id = data["event_id"]
        print(f"[vector_db] Received query for tag: {query}")

        # TODO: replace with your real embedding model call
        # e.g. tag_embedding = await embed_text(query)
        tag_embedding = [0.1, 0.2, 0.3]
        if query == "dog":
            tag_embedding = [1, 1, 1]
        if query == "cat":
            tag_embedding = [0, 0, 0]

        query_vector = np.array([tag_embedding], dtype="float32")
        distances, ids = index.search(query_vector, TOP_K)  # <-- fixed, not a URL

        similar_image_ids = []
        for i, faiss_id in enumerate(ids[0]):
            if faiss_id == -1:
                continue
            distance = float(distances[0][i])
            if distance <= EPSILON:
                doc = await collection.find_one(
                    {"faiss_id": int(faiss_id)},
                    {"_id": 0, "image_id": 1}
                )
                if doc:
                    similar_image_ids.append(doc["image_id"])

        await r.publish(
            "query.embedding_results",
            json.dumps({
                "event_id": event_id,
                "similar_image_ids": similar_image_ids
            })
        )

    except Exception as e:
        print("Query failed:", str(e))


