import json
import asyncio
from redis.asyncio import Redis

#Is responsible for uploading and querying the vector database for image embeddings.
#The vector database will store the image embeddings generated by the embedding service, 
# and will allow for efficient querying of similar images based on their embeddings.

#Listens for the embedding service to publish new embeddings, and stores them in the database.
#Listens for the CLI to query for similar images, and retrieves the relevant embeddings from the 
# database to return the results.

r = Redis(host='localhost', port=6379, decode_responses=True)
pubsub_embeds = r.pubsub()
pubsub_queries = r.pubsub()

#Gets service ready to listen
async def start():
    await pubsub_embeds.subscribe("image.embedding_results")
    print("[vector_db] Listening on image.embedding_results")
    await pubsub_queries.subscribe("query.images")
    print("[vector_db] Listening on query.images")
    

    await r.sadd("services_ready", "vector_db")
    await r.publish("service.ready", "vector_db")

    embed_task = asyncio.create_task(listen_embeddings())
    query_task = asyncio.create_task(listen_queries())

    try:
        await asyncio.gather(embed_task, query_task)
    except asyncio.CancelledError:
        print("[vector_db] Shutting down listener...")
    finally:
        embed_task.cancel()
        query_task.cancel()
        try:
            await asyncio.gather(embed_task, query_task)
        except asyncio.CancelledError:
            pass
        await r.srem("services_ready", "vector_db")

        await pubsub_embeds.unsubscribe("image.embedding_results")
        await pubsub_queries.unsubscribe("query.images")

        await pubsub_embeds.close()
        await pubsub_queries.close()
        await r.aclose()

#Listen Loop
async def listen_embeddings():
    async for message in pubsub_embeds.listen():
        if message["type"] == "message":
            await upload_embedding(message)

#Listen Loop
async def listen_queries():
    async for message in pubsub_queries.listen():
        if message["type"] == "message":
            await query_similar_images(message)

async def upload_embedding(message):
    data = json.loads(message["data"])
    image_id = data["image_id"]
    embedding = data["embedding"]

    print(f"[vector_db] Received embedding for image: {image_id}")

    # Code to upload the embedding data to the vector database
    
    #success return 

async def query_similar_images(message):
    data = json.loads(message["data"])
    query = data["tag"]

    print(f"[vector_db] Received query for tag: {query}")

    #Imagine we retrieve this from a model
    tag_embedding = [0.1, 0.2, 0.3]  

    #imagine we manage to get similar image ids based on the tag embedding
    similar_image_ids = [1, 2, 3]  
    
    await r.publish(
        "query.embedding_results",
        json.dumps({
            "similar_image_ids": similar_image_ids
        })  
    )
